<a href="https://colab.research.google.com/github/CauchyLee1981/colab/blob/master/wordToText.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
cd drive/My\ Drive/Colab\ Notebooks

/content/drive/My Drive/Colab Notebooks


In [12]:
import os
import numpy as np
from keras.utils import np_utils


def my_generator(path="data", batch_size=50, n_classes=2, frame_num=32, shift=8):
    key_point=25
    channel=3
    
    if not os.path.exists(path):
        print(path, "is not exist\n")
        return

    train_data = []
    counter = 0
    for root, folders, _ in os.walk(path): break
    print(root,folders)
    while True:
      for folder in folders:
        for root2, _, files in os.walk(os.path.join(root, folder)): break
        print("\n",root2,files)
        for file in files:
          with open(os.path.join(root2, file)) as tmp_file:
            a = tmp_file.read()
            b = np.array(a.split()).reshape(-1, key_point, channel)
            for i in range(5):
              start = i * shift +frame_num
              end = start + frame_num
              X = b[start:end]
              X = X.reshape(1, frame_num, key_point, channel)
              y = np_utils.to_categorical(int(folder), num_classes=n_classes)
              y = y.reshape(1, len(y))
              yield X, y



gen = my_generator()
i = 0

for X,y in gen:
  #print(X)
  print(y)
  if i >= 50: 
    break
  else:
    i=i+1


data ['000', '001']

 data/000 ['P01_01_00_4._body.txt', 'P01_01_00_0._body.txt', 'P01_01_00_3._body.txt', 'P01_01_00_2._body.txt', 'P01_01_00_1._body.txt']
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]

 data/001 ['P01_01_01_4._body.txt', 'P01_01_01_0._body.txt', 'P01_01_01_2._body.txt', 'P01_01_01_3._body.txt', 'P01_01_01_1._body.txt']
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]

 data/000 ['P01_01_00_4._body.txt', 'P01_01_00_0._body.txt', 'P01_01_00_3._body.txt', 'P01_01_00_2._body.txt', 'P01_01_00_1._body.txt']
[[1. 0.]]


In [14]:
import time

import argparse
import json
import os

from keras.callbacks import EarlyStopping, ReduceLROnPlateau
from keras.layers import *
from keras.layers.convolutional import *
from keras.layers.core import *
from keras.models import Model
from keras.optimizers import adam


def one_obj(frame_l=32, joint_n=25, joint_d=3, words_size=500):
    input_joints = Input(name='joints', shape=(frame_l, joint_n, joint_d))

    x = Conv2D(filters=64, kernel_size=(1, 1), padding='same')(input_joints)
    x = BatchNormalization()(x)
    x = LeakyReLU()(x)  # @LeakyReLU()(x)

    x = Conv2D(filters=32, kernel_size=(3, 1), padding='same')(x)
    x = BatchNormalization()(x)
    x = LeakyReLU()(x)  # LeakyReLU()(x)

    x = Permute((1, 3, 2))(x)

    x = Conv2D(filters=32, kernel_size=(3, 3), padding='same')(x)
    x = BatchNormalization()(x)
    x = LeakyReLU()(x)  # LeakyReLU()(x)
    x = MaxPool2D(pool_size=(2, 2))(x)
    x = Conv2D(filters=64, kernel_size=(3, 3), padding='same')(x)
    x = LeakyReLU()(x)  # BatchNormalization()(x)
    x = MaxPool2D(pool_size=(2, 2))(x)

    x = Conv2D(filters=128, kernel_size=(1, 1), padding='same')(x)
    x = BatchNormalization()(x)
    x = LeakyReLU()(x)  # LeakyReLU()(x)
    x = MaxPool2D(pool_size=(2, 2))(x)
    x = Dropout(0.1)(x)

    x = Conv2D(filters=256, kernel_size=(1, 1), padding='same')(x)
    x = BatchNormalization()(x)
    x = LeakyReLU()(x)  # LeakyReLU()(x)
    x = MaxPool2D(pool_size=(2, 2))(x)
    x = Dropout(0.1)(x)
    x = Flatten()(x)
    x = Dense(256)(x)
    x = LeakyReLU()(x)  # LeakyReLU()(x)
    x = Dense(words_size, activation='softmax')(x)
    return Model(input_joints, x)


model = one_obj(32, 25, 3, 2)
opt = adam(0.005, epsilon=1e-8)
model.compile(opt, 'categorical_crossentropy', metrics=['acc'])
model.summary()

early = EarlyStopping(monitor="loss", mode="min", patience=10)
lr_change = ReduceLROnPlateau(monitor="loss", verbose=1, factor=0.2, patience=100, min_lr=1e-8, cooldown=100)
lr_change.set_model(model)
lr_change.on_train_begin()
best_acc = 0.0







Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
joints (InputLayer)          (None, 32, 25, 3)         0         
_________________________________________________________________
conv2d_13 (Conv2D)           (None, 32, 25, 64)        256       
_________________________________________________________________
batch_normalization_11 (Batc (None, 32, 25, 64)        256       
_________________________________________________________________
leaky_re_lu_15 (LeakyReLU)   (None, 32, 25, 64)        0         
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 32, 25, 32)        6176      
_________________________________________________________________
batch_normalization_12 (Batc (None, 32, 25, 32)        128       
_________________________________________________________________
leaky_re_lu_16 (LeakyReLU)   (None, 32, 25, 32)        0   

In [16]:

train_generator = my_generator()

# Train model on dataset
model.fit_generator(generator=train_generator,
          steps_per_epoch=50,
          epochs=20)

Epoch 1/20
 1/50 [..............................] - ETA: 1s - loss: 1.1921e-07 - acc: 1.0000
 data/001 ['P01_01_01_4._body.txt', 'P01_01_01_0._body.txt', 'P01_01_01_2._body.txt', 'P01_01_01_3._body.txt', 'P01_01_01_1._body.txt']
28/50 [===============>..............] - ETA: 0s - loss: 8.0590 - acc: 0.5000
 data/000 ['P01_01_00_4._body.txt', 'P01_01_00_0._body.txt', 'P01_01_00_3._body.txt', 'P01_01_00_2._body.txt', 'P01_01_00_1._body.txt']
50/50 [==============================] - 1s 18ms/step - loss: 8.0590 - acc: 0.5000
Epoch 2/20
 1/50 [..............................] - ETA: 0s - loss: 1.1921e-07 - acc: 1.0000
 data/001 ['P01_01_01_4._body.txt', 'P01_01_01_0._body.txt', 'P01_01_01_2._body.txt', 'P01_01_01_3._body.txt', 'P01_01_01_1._body.txt']
28/50 [===============>..............] - ETA: 0s - loss: 8.0590 - acc: 0.5000
 data/000 ['P01_01_00_4._body.txt', 'P01_01_00_0._body.txt', 'P01_01_00_3._body.txt', 'P01_01_00_2._body.txt', 'P01_01_00_1._body.txt']
50/50 [========================